# Generated by Django 4.2.7 on 2025-11-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('add_numbers', 'Add Numbers'), ('send_email', 'Send Email'), ('process_data', 'Process Data')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict, help_text='Input parameters for the task')),
                ('result', models.TextField(blank=True, help_text='Task result/output', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if task failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Task duration in seconds', null=True)),
            ],
            options={
                'verbose_name': 'Task Result',
                'verbose_name_plural': 'Task Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
